from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "rooms" / "ambulance" / "optimized"


class ObjWriter:
    def __init__(self, name: str) -> None:
        self.name = name
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[tuple[str, tuple[int, ...]]] = []

    def vertex(self, x: float, y: float, z: float) -> int:
        self.vertices.append((x, y, z))
        return len(self.vertices)

    def face(self, material: str, indices: tuple[int, ...]) -> None:
        self.faces.append((material, indices))

    def box(
        self,
        cx: float,
        cy: float,
        cz: float,
        sx: float,
        sy: float,
        sz: float,
        material: str,
    ) -> None:
        x0, x1 = cx - sx * 0.5, cx + sx * 0.5
        y0, y1 = cy - sy * 0.5, cy + sy * 0.5
        z0, z1 = cz - sz * 0.5, cz + sz * 0.5
        v = [
            self.vertex(x0, y0, z0),
            self.vertex(x1, y0, z0),
            self.vertex(x1, y1, z0),
            self.vertex(x0, y1, z0),
            self.vertex(x0, y0, z1),
            self.vertex(x1, y0, z1),
            self.vertex(x1, y1, z1),
            self.vertex(x0, y1, z1),
        ]
        self.face(material, (v[0], v[1], v[2], v[3]))
        self.face(material, (v[5], v[4], v[7], v[6]))
        self.face(material, (v[4], v[0], v[3], v[7]))
        self.face(material, (v[1], v[5], v[6], v[2]))
        self.face(material, (v[3], v[2], v[6], v[7]))
        self.face(material, (v[4], v[5], v[1], v[0]))

    def cylinder_y(
        self,
        cx: float,
        cy: float,
        cz: float,
        radius: float,
        height: float,
        material: str,
        sides: int = 12,
    ) -> None:
        bottom: list[int] = []
        top: list[int] = []
        y0, y1 = cy - height * 0.5, cy + height * 0.5
        for i in range(sides):
            a = math.tau * i / sides
            x = cx + math.cos(a) * radius
            z = cz + math.sin(a) * radius
            bottom.append(self.vertex(x, y0, z))
            top.append(self.vertex(x, y1, z))
        for i in range(sides):
            self.face(material, (bottom[i], bottom[(i + 1) % sides], top[(i + 1) % sides], top[i]))
        self.face(material, tuple(reversed(bottom)))
        self.face(material, tuple(top))

    def write(self, filename: str) -> None:
        OUT.mkdir(parents=True, exist_ok=True)
        path = OUT / filename
        corner_uvs: list[tuple[float, float]] = []
        face_normals: list[tuple[float, float, float]] = []
        face_tokens: list[tuple[str, list[str]]] = []
        for material, indices in self.faces:
            points = [self.vertices[i - 1] for i in indices]
            normal = normal_for_face(points)
            normal_index = len(face_normals) + 1
            face_normals.append(normal)
            uvs = uvs_for_face(len(indices))
            tokens: list[str] = []
            for vertex_index, uv in zip(indices, uvs):
                corner_uvs.append(uv)
                uv_index = len(corner_uvs)
                tokens.append(f"{vertex_index}/{uv_index}/{normal_index}")
            face_tokens.append((material, tokens))

        lines = [
            "# Generated by tools/generate_ambulance_proxy_meshes.py",
            "mtllib ambulance_proxy_materials.mtl",
            f"o {self.name}",
        ]
        for x, y, z in self.vertices:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for u, v in corner_uvs:
            lines.append(f"vt {u:.6f} {v:.6f}")
        for x, y, z in face_normals:
            lines.append(f"vn {x:.6f} {y:.6f} {z:.6f}")
        current = ""
        for material, tokens in face_tokens:
            if material != current:
                lines.append(f"usemtl {material}")
                current = material
            lines.append("f " + " ".join(tokens))
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def normal_for_face(points: list[tuple[float, float, float]]) -> tuple[float, float, float]:
    if len(points) < 3:
        return (0.0, 1.0, 0.0)
    ax, ay, az = points[0]
    bx, by, bz = points[1]
    cx, cy, cz = points[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt((nx * nx) + (ny * ny) + (nz * nz))
    if length <= 1.0e-6:
        return (0.0, 1.0, 0.0)
    return (nx / length, ny / length, nz / length)


def uvs_for_face(count: int) -> list[tuple[float, float]]:
    if count == 3:
        return [(0.0, 0.0), (1.0, 0.0), (0.5, 1.0)]
    if count == 4:
        return [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
    result: list[tuple[float, float]] = []
    for i in range(count):
        a = math.tau * i / max(count, 1)
        result.append((0.5 + math.cos(a) * 0.5, 0.5 + math.sin(a) * 0.5))
    return result


def write_materials() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    materials = {
        "clinical_blue": ((0.56, 0.67, 0.72), (0.055, 0.060, 0.060), 22.0),
        "painted_metal": ((0.66, 0.69, 0.69), (0.26, 0.28, 0.27), 70.0),
        "dark_rubber": ((0.025, 0.029, 0.030), (0.012, 0.012, 0.012), 8.0),
        "screen_glass": ((0.010, 0.055, 0.042), (0.50, 0.70, 0.58), 128.0),
        "oxygen_green": ((0.055, 0.36, 0.16), (0.08, 0.11, 0.08), 28.0),
        "strap_red": ((0.42, 0.018, 0.012), (0.035, 0.020, 0.018), 16.0),
        "soft_white": ((0.86, 0.86, 0.82), (0.055, 0.055, 0.050), 24.0),
        "abs_panel": ((0.78, 0.78, 0.72), (0.075, 0.075, 0.065), 30.0),
        "abs_shadow": ((0.55, 0.57, 0.55), (0.050, 0.050, 0.048), 22.0),
        "rubber_floor": ((0.075, 0.083, 0.083), (0.018, 0.018, 0.016), 10.0),
        "ceiling_panel": ((0.80, 0.80, 0.74), (0.070, 0.070, 0.060), 28.0),
        "cabinet_off_white": ((0.83, 0.84, 0.79), (0.080, 0.080, 0.070), 36.0),
        "cabinet_glass": ((0.26, 0.34, 0.34), (0.35, 0.44, 0.40), 96.0),
        "linen_off_white": ((0.88, 0.88, 0.83), (0.018, 0.017, 0.015), 8.0),
        "blanket_desaturated_blue": ((0.35, 0.48, 0.55), (0.020, 0.020, 0.018), 9.0),
        "stainless": ((0.62, 0.64, 0.63), (0.44, 0.46, 0.43), 112.0),
        "monitor_green": ((0.06, 0.86, 0.34), (0.18, 0.40, 0.22), 82.0),
        "label_blue": ((0.12, 0.28, 0.44), (0.035, 0.045, 0.055), 18.0),
        "label_yellow": ((0.80, 0.62, 0.18), (0.045, 0.040, 0.025), 18.0),
        "paper_label": ((0.78, 0.76, 0.66), (0.018, 0.017, 0.014), 9.0),
        "amber_light": ((1.00, 0.76, 0.44), (0.18, 0.12, 0.06), 48.0),
        "grime": ((0.11, 0.105, 0.090), (0.006, 0.006, 0.005), 6.0),
    }
    lines: list[str] = ["# Generated ambulance proxy material library"]
    for name, (color, specular, shininess) in materials.items():
        r, g, b = color
        sr, sg, sb = specular
        lines.extend([
            f"newmtl {name}",
            f"Kd {r:.3f} {g:.3f} {b:.3f}",
            f"Ks {sr:.3f} {sg:.3f} {sb:.3f}",
            f"Ns {shininess:.1f}",
        ])
    (OUT / "ambulance_proxy_materials.mtl").write_text("\n".join(lines) + "\n", encoding="utf-8")


def stretcher() -> None:
    w = ObjWriter("patient_stretcher_proxy")
    w.box(0.0, 0.08, 0.0, 0.72, 0.10, 1.75, "painted_metal")
    w.box(0.0, 0.22, -0.10, 0.68, 0.14, 1.48, "soft_white")
    w.box(0.0, 0.33, 0.66, 0.50, 0.11, 0.34, "soft_white")
    for x in (-0.46, 0.46):
        w.box(x, 0.36, 0.0, 0.035, 0.12, 1.72, "painted_metal")
        w.box(x, -0.36, -0.55, 0.05, 0.72, 0.05, "painted_metal")
        w.box(x, -0.36, 0.55, 0.05, 0.72, 0.05, "painted_metal")
    for z in (-0.70, 0.70):
        w.cylinder_y(-0.33, -0.82, z, 0.07, 0.045, "dark_rubber", 12)
        w.cylinder_y(0.33, -0.82, z, 0.07, 0.045, "dark_rubber", 12)
    w.write("patient_stretcher_proxy.obj")


def cabinet() -> None:
    w = ObjWriter("medical_cabinet_proxy")
    w.box(0.0, 0.0, 0.0, 1.70, 1.62, 0.52, "painted_metal")
    w.box(-0.43, 0.0, -0.28, 0.78, 1.45, 0.035, "soft_white")
    w.box(0.43, 0.0, -0.28, 0.78, 1.45, 0.035, "soft_white")
    for y in (-0.42, 0.0, 0.42):
        w.box(0.0, y, -0.33, 1.55, 0.035, 0.08, "painted_metal")
    w.box(0.0, -0.86, 0.0, 1.78, 0.10, 0.60, "dark_rubber")
    w.write("medical_cabinet_proxy.obj")


def equipment() -> None:
    w = ObjWriter("medical_equipment_rack_proxy")
    for x in (-0.78, 0.78):
        for z in (-0.43, 0.43):
            w.box(x, 0.0, z, 0.06, 1.18, 0.06, "painted_metal")
    for y in (-0.48, 0.0, 0.48):
        w.box(0.0, y, 0.0, 1.65, 0.05, 0.88, "painted_metal")
    w.box(-0.30, 0.30, -0.18, 0.70, 0.38, 0.36, "soft_white")
    w.box(0.42, 0.28, -0.18, 0.42, 0.30, 0.30, "screen_glass")
    w.box(-0.36, -0.26, -0.10, 0.58, 0.28, 0.42, "painted_metal")
    w.box(0.35, -0.30, -0.08, 0.48, 0.22, 0.36, "soft_white")
    w.write("medical_equipment_rack_proxy.obj")


def monitor() -> None:
    w = ObjWriter("patient_monitor_proxy")
    w.box(0.0, 0.22, -0.03, 1.25, 0.66, 0.18, "painted_metal")
    w.box(0.0, 0.24, -0.14, 1.02, 0.46, 0.035, "screen_glass")
    w.box(0.0, -0.30, 0.02, 0.12, 0.72, 0.12, "painted_metal")
    w.box(0.0, -0.72, 0.02, 0.60, 0.08, 0.38, "dark_rubber")
    w.box(0.0, -0.10, -0.30, 0.72, 0.08, 0.08, "painted_metal")
    w.write("patient_monitor_proxy.obj")


def oxygen() -> None:
    w = ObjWriter("oxygen_cylinders_proxy")
    for x in (-0.30, 0.30):
        w.cylinder_y(x, 0.0, 0.0, 0.19, 1.58, "oxygen_green", 16)
        w.box(x, 0.84, 0.0, 0.22, 0.10, 0.22, "painted_metal")
        w.box(x, -0.02, -0.22, 0.50, 0.07, 0.06, "painted_metal")
        w.box(x, 0.42, -0.22, 0.50, 0.07, 0.06, "painted_metal")
    w.box(0.0, 0.0, 0.25, 0.86, 1.70, 0.08, "painted_metal")
    w.box(0.0, -0.86, 0.0, 0.90, 0.10, 0.52, "dark_rubber")
    w.write("oxygen_cylinders_proxy.obj")


def medical_bag() -> None:
    w = ObjWriter("medical_bag_proxy")
    w.box(0.0, -0.12, 0.0, 1.55, 0.78, 0.84, "strap_red")
    w.box(0.0, 0.30, 0.0, 1.40, 0.12, 0.72, "strap_red")
    w.box(0.0, 0.45, -0.02, 0.80, 0.12, 0.14, "dark_rubber")
    w.box(0.0, -0.10, -0.46, 1.68, 0.08, 0.08, "dark_rubber")
    w.box(-0.38, -0.10, -0.50, 0.10, 0.86, 0.08, "dark_rubber")
    w.box(0.38, -0.10, -0.50, 0.10, 0.86, 0.08, "dark_rubber")
    w.write("medical_bag_proxy.obj")


def iv_stand() -> None:
    w = ObjWriter("iv_stand_proxy")
    w.cylinder_y(0.0, 0.0, 0.0, 0.025, 1.74, "painted_metal", 10)
    w.box(0.0, 0.90, 0.0, 0.55, 0.035, 0.035, "painted_metal")
    w.box(-0.26, 0.82, 0.0, 0.035, 0.18, 0.035, "painted_metal")
    w.box(0.26, 0.82, 0.0, 0.035, 0.18, 0.035, "painted_metal")
    for angle in (0.0, math.tau / 3.0, 2.0 * math.tau / 3.0):
        x = math.cos(angle) * 0.23
        z = math.sin(angle) * 0.23
        w.box(x * 0.5, -0.88, z * 0.5, abs(x) + 0.05, 0.045, abs(z) + 0.05, "painted_metal")
    w.cylinder_y(0.0, -0.91, 0.0, 0.07, 0.05, "dark_rubber", 12)
    w.write("iv_stand_proxy.obj")


def main() -> None:
    write_materials()
    stretcher()
    cabinet()
    equipment()
    monitor()
    oxygen()
    medical_bag()
    iv_stand()


if __name__ == "__main__":
    main()
