from __future__ import annotations

import math
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "rooms" / "hospital_ward" / "clean"


class ObjWriter:
    def __init__(self, name: str) -> None:
        self.name = name
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[tuple[str, tuple[int, ...]]] = []

    def vertex(self, x: float, y: float, z: float) -> int:
        self.vertices.append((x, y, z))
        return len(self.vertices)

    def face(self, material: str, indices: tuple[int, ...]) -> None:
        self.faces.append((material, indices))

    def box(
        self,
        cx: float,
        cy: float,
        cz: float,
        sx: float,
        sy: float,
        sz: float,
        material: str,
    ) -> None:
        x0, x1 = cx - sx * 0.5, cx + sx * 0.5
        y0, y1 = cy - sy * 0.5, cy + sy * 0.5
        z0, z1 = cz - sz * 0.5, cz + sz * 0.5
        v = [
            self.vertex(x0, y0, z0),
            self.vertex(x1, y0, z0),
            self.vertex(x1, y1, z0),
            self.vertex(x0, y1, z0),
            self.vertex(x0, y0, z1),
            self.vertex(x1, y0, z1),
            self.vertex(x1, y1, z1),
            self.vertex(x0, y1, z1),
        ]
        self.face(material, (v[0], v[1], v[2], v[3]))
        self.face(material, (v[5], v[4], v[7], v[6]))
        self.face(material, (v[4], v[0], v[3], v[7]))
        self.face(material, (v[1], v[5], v[6], v[2]))
        self.face(material, (v[3], v[2], v[6], v[7]))
        self.face(material, (v[4], v[5], v[1], v[0]))

    def panel(
        self,
        center: tuple[float, float, float],
        u: tuple[float, float, float],
        v: tuple[float, float, float],
        material: str,
    ) -> None:
        cx, cy, cz = center
        ux, uy, uz = u
        vx, vy, vz = v
        ids = (
            self.vertex(cx - ux - vx, cy - uy - vy, cz - uz - vz),
            self.vertex(cx + ux - vx, cy + uy - vy, cz + uz - vz),
            self.vertex(cx + ux + vx, cy + uy + vy, cz + uz + vz),
            self.vertex(cx - ux + vx, cy - uy + vy, cz - uz + vz),
        )
        self.face(material, ids)

    def cylinder_y(
        self,
        cx: float,
        cy: float,
        cz: float,
        radius: float,
        height: float,
        material: str,
        sides: int = 12,
    ) -> None:
        bottom: list[int] = []
        top: list[int] = []
        y0, y1 = cy - height * 0.5, cy + height * 0.5
        for i in range(sides):
            a = math.tau * i / sides
            x = cx + math.cos(a) * radius
            z = cz + math.sin(a) * radius
            bottom.append(self.vertex(x, y0, z))
            top.append(self.vertex(x, y1, z))
        for i in range(sides):
            self.face(material, (bottom[i], bottom[(i + 1) % sides], top[(i + 1) % sides], top[i]))
        self.face(material, tuple(reversed(bottom)))
        self.face(material, tuple(top))

    def write(self, filename: str) -> None:
        OUT.mkdir(parents=True, exist_ok=True)
        lines = [
            "# Generated by tools/generate_hospital_ward_assets.py",
            "mtllib hospital_ward_materials.mtl",
            f"o {self.name}",
        ]
        corner_uvs: list[tuple[float, float]] = []
        normals: list[tuple[float, float, float]] = []
        token_faces: list[tuple[str, list[str]]] = []
        for material, indices in self.faces:
            points = [self.vertices[i - 1] for i in indices]
            normal = normal_for_face(points)
            normals.append(normal)
            normal_id = len(normals)
            uvs = uvs_for_face(len(indices))
            tokens: list[str] = []
            for index, uv in zip(indices, uvs):
                corner_uvs.append(uv)
                tokens.append(f"{index}/{len(corner_uvs)}/{normal_id}")
            token_faces.append((material, tokens))

        for x, y, z in self.vertices:
            lines.append(f"v {x:.6f} {y:.6f} {z:.6f}")
        for u, v in corner_uvs:
            lines.append(f"vt {u:.6f} {v:.6f}")
        for x, y, z in normals:
            lines.append(f"vn {x:.6f} {y:.6f} {z:.6f}")

        current = ""
        for material, tokens in token_faces:
            if material != current:
                lines.append(f"usemtl {material}")
                current = material
            lines.append("f " + " ".join(tokens))
        (OUT / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")


def normal_for_face(points: list[tuple[float, float, float]]) -> tuple[float, float, float]:
    if len(points) < 3:
        return (0.0, 1.0, 0.0)
    ax, ay, az = points[0]
    bx, by, bz = points[1]
    cx, cy, cz = points[2]
    ux, uy, uz = bx - ax, by - ay, bz - az
    vx, vy, vz = cx - ax, cy - ay, cz - az
    nx = uy * vz - uz * vy
    ny = uz * vx - ux * vz
    nz = ux * vy - uy * vx
    length = math.sqrt(nx * nx + ny * ny + nz * nz)
    if length <= 1.0e-6:
        return (0.0, 1.0, 0.0)
    return (nx / length, ny / length, nz / length)


def uvs_for_face(count: int) -> list[tuple[float, float]]:
    if count == 3:
        return [(0.0, 0.0), (1.0, 0.0), (0.5, 1.0)]
    if count == 4:
        return [(0.0, 0.0), (1.0, 0.0), (1.0, 1.0), (0.0, 1.0)]
    return [
        (0.5 + math.cos(math.tau * i / count) * 0.5, 0.5 + math.sin(math.tau * i / count) * 0.5)
        for i in range(count)
    ]


def write_materials() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    materials = {
        "wall_cold": ((0.73, 0.76, 0.70), (0.030, 0.030, 0.026), 14.0),
        "wall_trim": ((0.48, 0.55, 0.50), (0.045, 0.050, 0.044), 18.0),
        "floor_blue": ((0.12, 0.13, 0.14), (0.030, 0.030, 0.028), 16.0),
        "ceiling_dim": ((0.68, 0.70, 0.66), (0.035, 0.035, 0.030), 16.0),
        "metal": ((0.66, 0.67, 0.65), (0.36, 0.37, 0.34), 108.0),
        "bed_sheet": ((0.86, 0.85, 0.80), (0.018, 0.017, 0.014), 8.0),
        "blanket": ((0.56, 0.63, 0.58), (0.018, 0.018, 0.015), 9.0),
        "linen_shadow": ((0.48, 0.50, 0.46), (0.012, 0.012, 0.010), 7.0),
        "dark_glass": ((0.02, 0.03, 0.04), (0.42, 0.46, 0.50), 120.0),
        "monitor_glass": ((0.01, 0.18, 0.11), (0.24, 0.50, 0.32), 112.0),
        "curtain": ((0.72, 0.76, 0.70), (0.018, 0.018, 0.015), 9.0),
        "cabinet": ((0.58, 0.61, 0.57), (0.070, 0.075, 0.065), 34.0),
        "warning_red": ((0.40, 0.05, 0.04), (0.030, 0.018, 0.016), 14.0),
        "medical_green": ((0.05, 0.35, 0.19), (0.055, 0.090, 0.060), 24.0),
        "fluid_blue": ((0.38, 0.58, 0.66), (0.070, 0.110, 0.120), 36.0),
        "signal_yellow": ((0.90, 0.70, 0.18), (0.055, 0.040, 0.018), 18.0),
        "rubber_dark": ((0.035, 0.045, 0.050), (0.012, 0.012, 0.012), 8.0),
        "soft_light": ((0.96, 0.88, 0.68), (0.16, 0.11, 0.06), 42.0),
        "paper": ((0.86, 0.84, 0.76), (0.015, 0.014, 0.012), 8.0),
        "door": ((0.40, 0.43, 0.40), (0.055, 0.058, 0.050), 24.0),
        "outlet_white": ((0.80, 0.79, 0.72), (0.080, 0.080, 0.070), 30.0),
        "gas_oxygen": ((0.12, 0.38, 0.22), (0.045, 0.070, 0.050), 24.0),
        "gas_air": ((0.36, 0.52, 0.62), (0.065, 0.090, 0.105), 30.0),
        "gas_vacuum": ((0.48, 0.38, 0.30), (0.050, 0.040, 0.032), 22.0),
        "vinyl_scuff": ((0.21, 0.21, 0.20), (0.014, 0.014, 0.013), 9.0),
        "wall_stain": ((0.42, 0.45, 0.40), (0.010, 0.010, 0.008), 6.0),
        "rail_bumper": ((0.62, 0.66, 0.60), (0.050, 0.055, 0.047), 18.0),
        "sterile_blue": ((0.28, 0.48, 0.62), (0.060, 0.090, 0.110), 30.0),
        "tape": ((0.88, 0.86, 0.76), (0.015, 0.014, 0.012), 8.0),
        "warm_indicator": ((1.00, 0.58, 0.18), (0.15, 0.07, 0.02), 40.0),
        "old_bruise": ((0.24, 0.18, 0.16), (0.006, 0.005, 0.004), 6.0),
    }
    lines = ["# Generated hospital ward material library"]
    for name, (color, specular, shininess) in materials.items():
        r, g, b = color
        sr, sg, sb = specular
        lines.extend([
            f"newmtl {name}",
            f"Kd {r:.3f} {g:.3f} {b:.3f}",
            f"Ks {sr:.3f} {sg:.3f} {sb:.3f}",
            f"Ns {shininess:.1f}",
        ])
    (OUT / "hospital_ward_materials.mtl").write_text("\n".join(lines) + "\n", encoding="utf-8")


def shell() -> None:
    w = ObjWriter("hospital_ward_shell")
    w.box(0.0, -0.04, 0.0, 4.4, 0.08, 5.4, "floor_blue")
    w.box(0.0, 2.55, 0.0, 4.4, 0.08, 5.4, "ceiling_dim")
    w.box(-2.2, 1.25, 0.0, 0.08, 2.58, 5.4, "wall_cold")
    w.box(2.2, 1.25, 0.0, 0.08, 2.58, 5.4, "wall_cold")
    w.box(0.0, 1.25, -2.7, 4.4, 2.58, 0.08, "wall_cold")
    w.box(0.0, 1.25, 2.7, 4.4, 2.58, 0.08, "wall_cold")
    w.box(0.0, 0.11, -2.64, 4.18, 0.14, 0.06, "wall_trim")
    w.box(0.0, 0.11, 2.64, 4.18, 0.14, 0.06, "wall_trim")
    w.box(-2.14, 0.11, 0.0, 0.06, 0.14, 5.12, "wall_trim")
    w.box(2.14, 0.11, 0.0, 0.06, 0.14, 5.12, "wall_trim")
    w.box(0.0, 0.86, -2.635, 4.05, 0.10, 0.045, "rail_bumper")
    w.box(-2.135, 0.86, 0.0, 0.045, 0.10, 5.00, "rail_bumper")
    w.box(2.135, 0.86, -0.42, 0.045, 0.10, 4.12, "rail_bumper")
    w.box(0.0, 0.28, -2.638, 4.08, 0.09, 0.035, "wall_stain")
    w.box(-2.138, 0.32, 0.68, 0.035, 0.10, 1.20, "wall_stain")
    w.box(0.42, 0.012, -0.30, 1.10, 0.018, 0.15, "vinyl_scuff")
    w.box(-0.92, 0.013, 1.34, 0.74, 0.016, 0.12, "vinyl_scuff")
    w.box(1.54, 0.014, -1.18, 0.40, 0.017, 0.60, "vinyl_scuff")
    for z in (-1.86, -0.92, 0.18, 1.26):
        w.box(0.0, 0.018, z, 3.65, 0.016, 0.030, "old_bruise")
    w.box(-2.23, 1.52, -0.75, 0.035, 0.92, 1.32, "dark_glass")
    w.box(-2.25, 1.52, -0.75, 0.08, 1.08, 1.48, "metal")
    w.box(-2.28, 1.52, -0.75, 0.03, 0.84, 1.20, "dark_glass")
    w.box(-2.17, 0.92, -0.75, 0.16, 0.08, 1.52, "metal")
    w.box(-2.17, 1.52, -0.75, 0.08, 0.05, 1.26, "metal")
    w.box(-2.17, 1.52, -0.75, 0.08, 0.88, 0.035, "metal")
    w.box(0.0, 2.46, -0.15, 1.40, 0.06, 0.22, "metal")
    w.box(-1.70, 1.30, -2.63, 0.52, 0.42, 0.06, "paper")
    w.box(-1.70, 1.18, -2.66, 0.38, 0.026, 0.020, "warning_red")
    w.box(-1.92, 0.98, -2.64, 0.34, 0.22, 0.030, "outlet_white")
    for x in (-2.00, -1.84):
        w.box(x, 0.98, -2.666, 0.035, 0.075, 0.014, "rubber_dark")
    w.box(2.138, 1.72, -1.42, 0.035, 0.34, 0.46, "paper")
    w.box(2.162, 1.82, -1.42, 0.018, 0.028, 0.36, "warning_red")
    w.box(2.164, 1.70, -1.42, 0.018, 0.024, 0.30, "medical_green")
    w.write("hospital_ward_shell.obj")


def bed() -> None:
    w = ObjWriter("hospital_bed")
    w.box(0.0, 0.54, 0.0, 1.12, 0.12, 2.20, "metal")
    w.box(0.0, 0.64, 0.0, 1.02, 0.12, 2.04, "linen_shadow")
    w.box(0.0, 0.75, 0.08, 0.98, 0.18, 1.82, "bed_sheet")
    w.box(0.0, 0.88, -0.42, 0.92, 0.10, 1.04, "blanket")
    w.box(0.0, 0.95, 0.05, 0.88, 0.034, 0.060, "linen_shadow")
    w.box(-0.26, 0.955, -0.18, 0.035, 0.030, 1.10, "linen_shadow")
    w.box(0.03, 0.962, -0.20, 0.030, 0.026, 1.00, "linen_shadow")
    w.box(0.31, 0.954, -0.22, 0.034, 0.030, 0.94, "linen_shadow")
    w.box(-0.37, 0.93, -0.54, 0.16, 0.025, 0.72, "bed_sheet")
    w.box(0.38, 0.925, -0.48, 0.14, 0.022, 0.68, "bed_sheet")
    for z in (-0.64, -0.28, 0.18):
        w.box(0.0, 1.015, z, 1.04, 0.024, 0.046, "tape")
        w.box(-0.52, 1.030, z, 0.055, 0.034, 0.064, "metal")
    w.box(0.28, 1.018, -0.80, 0.20, 0.022, 0.09, "sterile_blue")
    w.box(0.0, 0.96, 0.78, 0.76, 0.14, 0.34, "bed_sheet")
    w.box(-0.20, 1.035, 0.78, 0.030, 0.025, 0.30, "linen_shadow")
    w.box(0.22, 1.030, 0.77, 0.032, 0.024, 0.28, "linen_shadow")
    w.box(0.0, 1.04, 1.08, 1.14, 0.72, 0.065, "metal")
    w.box(0.0, 0.91, -1.09, 1.04, 0.44, 0.065, "metal")
    w.box(0.0, 1.26, 1.055, 0.96, 0.055, 0.050, "rail_bumper")
    w.box(0.0, 1.02, -1.085, 0.82, 0.050, 0.050, "rail_bumper")
    for x in (-0.62, 0.62):
        w.box(x, 0.88, -0.20, 0.045, 0.34, 1.20, "metal")
        w.box(x, 1.08, -0.20, 0.055, 0.05, 1.16, "metal")
        for z in (-0.68, -0.30, 0.08):
            w.box(x, 0.98, z, 0.040, 0.23, 0.035, "metal")
        w.box(x, 0.39, -0.82, 0.05, 0.70, 0.06, "metal")
        w.box(x, 0.39, 0.82, 0.05, 0.70, 0.06, "metal")
    for z in (-0.82, 0.82):
        w.cylinder_y(-0.43, 0.06, z, 0.08, 0.055, "metal", 12)
        w.cylinder_y(0.43, 0.06, z, 0.08, 0.055, "metal", 12)
        w.cylinder_y(-0.43, 0.035, z, 0.050, 0.050, "rubber_dark", 12)
        w.cylinder_y(0.43, 0.035, z, 0.050, 0.050, "rubber_dark", 12)
    w.write("hospital_bed.obj")


def bedside_table() -> None:
    w = ObjWriter("bedside_table")
    w.box(0.0, 0.42, 0.0, 0.62, 0.84, 0.50, "cabinet")
    w.box(0.0, 0.84, -0.02, 0.64, 0.035, 0.52, "metal")
    w.box(0.0, 0.70, -0.27, 0.52, 0.18, 0.04, "paper")
    w.box(0.0, 0.72, -0.292, 0.44, 0.022, 0.018, "wall_stain")
    w.box(0.0, 0.42, -0.27, 0.52, 0.22, 0.04, "cabinet")
    w.box(0.0, 0.12, -0.27, 0.52, 0.22, 0.04, "cabinet")
    w.box(0.0, 0.44, -0.31, 0.30, 0.035, 0.035, "metal")
    w.box(0.0, 0.14, -0.31, 0.30, 0.035, 0.035, "metal")
    w.box(0.0, 0.95, 0.0, 0.66, 0.06, 0.54, "metal")
    w.box(0.18, 1.02, -0.04, 0.14, 0.12, 0.14, "bed_sheet")
    w.box(-0.11, 1.015, -0.16, 0.24, 0.020, 0.16, "paper")
    w.box(-0.11, 1.032, -0.16, 0.18, 0.014, 0.018, "medical_green")
    w.cylinder_y(-0.18, 1.03, 0.08, 0.055, 0.12, "fluid_blue", 12)
    w.box(0.20, 1.045, 0.16, 0.22, 0.018, 0.12, "tape")
    w.box(0.20, 1.060, 0.16, 0.12, 0.014, 0.020, "warning_red")
    w.box(-0.24, 1.052, 0.12, 0.12, 0.018, 0.20, "sterile_blue")
    w.write("bedside_table.obj")


def iv_stand() -> None:
    w = ObjWriter("ward_iv_stand")
    w.cylinder_y(0.0, 0.88, 0.0, 0.025, 1.72, "metal", 12)
    w.box(0.0, 1.76, 0.0, 0.54, 0.035, 0.035, "metal")
    w.box(-0.25, 1.60, 0.0, 0.035, 0.32, 0.035, "metal")
    w.box(0.25, 1.60, 0.0, 0.035, 0.32, 0.035, "metal")
    w.box(-0.24, 1.36, 0.0, 0.18, 0.35, 0.06, "bed_sheet")
    w.box(-0.24, 1.31, -0.035, 0.12, 0.24, 0.025, "fluid_blue")
    w.box(-0.24, 1.12, 0.0, 0.025, 0.48, 0.025, "metal")
    w.box(-0.17, 1.00, 0.0, 0.035, 0.14, 0.025, "fluid_blue")
    w.box(-0.13, 0.78, 0.0, 0.018, 0.40, 0.018, "rubber_dark")
    w.box(-0.04, 0.60, 0.0, 0.20, 0.014, 0.018, "rubber_dark")
    w.box(0.13, 0.53, 0.0, 0.018, 0.16, 0.018, "rubber_dark")
    w.box(0.0, 0.03, 0.0, 0.70, 0.06, 0.70, "metal")
    w.write("iv_stand.obj")


def monitor() -> None:
    w = ObjWriter("ward_patient_monitor")
    w.box(0.0, 1.18, 0.0, 0.72, 0.44, 0.16, "rubber_dark")
    w.box(0.0, 1.19, -0.095, 0.58, 0.32, 0.035, "monitor_glass")
    w.box(-0.12, 1.22, -0.118, 0.17, 0.016, 0.014, "medical_green")
    w.box(0.08, 1.26, -0.118, 0.13, 0.016, 0.014, "medical_green")
    w.box(0.23, 1.16, -0.118, 0.08, 0.016, 0.014, "medical_green")
    w.box(-0.24, 1.10, -0.118, 0.06, 0.016, 0.014, "signal_yellow")
    w.box(-0.12, 1.10, -0.118, 0.06, 0.016, 0.014, "warning_red")
    w.box(0.00, 1.10, -0.118, 0.06, 0.016, 0.014, "fluid_blue")
    w.box(-0.38, 0.80, 0.03, 0.06, 0.78, 0.06, "metal")
    w.box(-0.16, 0.43, 0.02, 0.56, 0.08, 0.32, "metal")
    w.box(0.28, 0.88, -0.03, 0.18, 0.08, 0.08, "warning_red")
    w.box(0.28, 0.99, -0.092, 0.16, 0.024, 0.018, "warm_indicator")
    w.box(0.10, 0.99, -0.092, 0.08, 0.020, 0.018, "sterile_blue")
    w.box(-0.48, 0.74, 0.05, 0.025, 0.36, 0.025, "rubber_dark")
    w.box(-0.43, 0.63, -0.03, 0.18, 0.018, 0.025, "rubber_dark")
    w.box(-0.35, 0.56, -0.03, 0.018, 0.14, 0.025, "rubber_dark")
    w.write("patient_monitor.obj")


def curtain() -> None:
    w = ObjWriter("privacy_curtain")
    w.box(0.0, 2.05, 0.0, 1.70, 0.045, 0.045, "metal")
    for i in range(9):
        x = -0.80 + i * 0.20
        offset = 0.04 if i % 2 == 0 else -0.04
        w.panel((x, 1.16, offset), (0.060, 0.0, 0.0), (0.0, 0.80, 0.032), "curtain")
        w.box(x, 2.00, offset, 0.040, 0.080, 0.030, "metal")
    w.write("privacy_curtain.obj")


def door() -> None:
    w = ObjWriter("ward_door")
    w.box(0.0, 1.06, 0.0, 0.86, 2.12, 0.08, "door")
    w.box(0.0, 2.18, -0.01, 1.04, 0.10, 0.12, "metal")
    w.box(-0.52, 1.10, -0.01, 0.10, 2.28, 0.12, "metal")
    w.box(0.52, 1.10, -0.01, 0.10, 2.28, 0.12, "metal")
    w.box(-0.22, 1.42, -0.06, 0.32, 0.20, 0.035, "dark_glass")
    w.box(0.34, 1.00, -0.08, 0.12, 0.06, 0.08, "metal")
    w.box(0.0, 0.24, -0.055, 0.62, 0.18, 0.035, "metal")
    w.write("ward_door.obj")


def medical_headwall() -> None:
    w = ObjWriter("ward_medical_headwall")
    w.box(0.0, 1.48, 0.0, 1.70, 0.34, 0.065, "cabinet")
    w.box(0.0, 1.66, -0.045, 1.58, 0.060, 0.035, "metal")
    w.box(0.0, 1.30, -0.045, 1.48, 0.055, 0.035, "metal")
    for x, mat in [(-0.58, "gas_oxygen"), (-0.40, "gas_air"), (-0.22, "gas_vacuum")]:
        w.box(x, 1.50, -0.058, 0.115, 0.115, 0.026, mat)
        w.cylinder_y(x, 1.50, -0.074, 0.040, 0.020, "metal", 14)
        w.box(x, 1.61, -0.060, 0.11, 0.035, 0.018, "paper")
    for x in (0.12, 0.32, 0.52):
        w.box(x, 1.50, -0.058, 0.13, 0.16, 0.026, "outlet_white")
        w.box(x - 0.025, 1.525, -0.077, 0.018, 0.050, 0.010, "rubber_dark")
        w.box(x + 0.025, 1.525, -0.077, 0.018, 0.050, 0.010, "rubber_dark")
        w.box(x, 1.452, -0.077, 0.052, 0.012, 0.010, "rubber_dark")
    w.box(0.70, 1.63, -0.05, 0.20, 0.08, 0.025, "paper")
    w.box(0.69, 1.57, -0.056, 0.14, 0.014, 0.016, "warning_red")
    w.box(0.70, 1.45, -0.058, 0.22, 0.050, 0.020, "warm_indicator")
    w.box(0.70, 1.42, -0.062, 0.16, 0.016, 0.014, "tape")
    w.box(0.58, 1.30, -0.04, 0.035, 0.32, 0.030, "rubber_dark")
    w.box(0.48, 1.18, -0.05, 0.22, 0.024, 0.024, "rubber_dark")
    w.box(-0.42, 1.24, -0.048, 0.030, 0.28, 0.028, "rubber_dark")
    w.box(-0.30, 1.13, -0.048, 0.24, 0.022, 0.026, "rubber_dark")
    w.box(-0.02, 1.72, -0.060, 0.30, 0.12, 0.022, "dark_glass")
    w.write("medical_headwall.obj")


def overbed_light() -> None:
    w = ObjWriter("ward_overbed_light")
    w.box(0.0, 2.06, 0.0, 1.34, 0.11, 0.08, "metal")
    w.box(0.0, 1.99, -0.045, 1.08, 0.035, 0.035, "soft_light")
    w.box(-0.30, 1.955, -0.048, 0.18, 0.026, 0.026, "warm_indicator")
    w.box(0.34, 1.955, -0.048, 0.14, 0.022, 0.026, "soft_light")
    w.box(-0.58, 2.00, -0.02, 0.045, 0.12, 0.04, "metal")
    w.box(0.58, 2.00, -0.02, 0.045, 0.12, 0.04, "metal")
    w.write("overbed_light.obj")


def clinical_details() -> None:
    w = ObjWriter("ward_clinical_details")

    # Bed call unit and cable, visible from the wakeup camera.
    w.box(0.68, 0.98, 1.26, 0.12, 0.04, 0.18, "signal_yellow")
    w.box(0.68, 1.00, 1.20, 0.045, 0.016, 0.045, "warning_red")
    w.box(0.62, 0.94, 1.02, 0.025, 0.025, 0.48, "rubber_dark")
    w.box(0.44, 0.92, 0.79, 0.38, 0.018, 0.025, "rubber_dark")
    w.box(0.52, 0.935, 0.96, 0.18, 0.016, 0.020, "sterile_blue")

    # Monitor leads running toward the patient, kept as simple boxes for runtime cost.
    w.box(-0.70, 0.99, 0.88, 0.56, 0.018, 0.022, "rubber_dark")
    w.box(-0.42, 0.98, 0.74, 0.024, 0.018, 0.30, "rubber_dark")
    w.box(-0.28, 0.99, 0.61, 0.20, 0.014, 0.020, "medical_green")
    w.box(-0.52, 1.04, 1.02, 0.030, 0.020, 0.34, "rubber_dark")
    w.box(-0.18, 1.01, 0.48, 0.22, 0.014, 0.018, "warning_red")
    w.box(0.12, 1.005, 0.43, 0.28, 0.014, 0.018, "fluid_blue")
    w.box(-0.04, 1.024, 0.36, 0.16, 0.014, 0.018, "warm_indicator")

    # Patient wrist band and small clipped chart near the bedside table.
    w.box(0.34, 0.99, 0.18, 0.24, 0.018, 0.050, "paper")
    w.box(0.43, 1.00, 0.18, 0.040, 0.020, 0.055, "signal_yellow")
    w.box(1.18, 1.02, 1.15, 0.30, 0.035, 0.22, "paper")
    w.box(1.18, 1.045, 1.02, 0.24, 0.018, 0.025, "metal")
    w.box(1.04, 1.065, 1.15, 0.014, 0.018, 0.16, "medical_green")
    w.box(1.14, 1.068, 1.15, 0.014, 0.018, 0.18, "wall_stain")
    w.box(1.24, 1.071, 1.15, 0.014, 0.018, 0.14, "warning_red")
    w.box(1.34, 1.060, 1.15, 0.014, 0.018, 0.15, "sterile_blue")

    # Wall clock, corridor notice and scuffed floor strip to make the room feel used.
    w.cylinder_y(1.64, 1.72, -2.60, 0.16, 0.035, "metal", 16)
    w.box(1.64, 1.72, -2.625, 0.23, 0.23, 0.020, "paper")
    w.box(1.64, 1.72, -2.642, 0.012, 0.11, 0.012, "rubber_dark")
    w.box(1.69, 1.72, -2.642, 0.10, 0.012, 0.012, "rubber_dark")
    w.box(-1.22, 1.42, -2.63, 0.56, 0.30, 0.025, "paper")
    w.box(-1.22, 1.31, -2.65, 0.46, 0.026, 0.018, "warning_red")
    w.box(-1.86, 1.04, -2.63, 0.42, 0.25, 0.025, "paper")
    w.box(-1.86, 1.13, -2.65, 0.34, 0.024, 0.018, "medical_green")
    w.box(-1.86, 1.02, -2.65, 0.28, 0.020, 0.018, "wall_stain")
    w.box(0.15, 0.012, -0.52, 1.30, 0.018, 0.18, "wall_trim")
    w.box(-0.52, 0.014, 1.08, 0.48, 0.016, 0.10, "vinyl_scuff")
    w.box(0.78, 0.015, 1.72, 0.36, 0.016, 0.12, "vinyl_scuff")
    w.box(-2.105, 1.05, 1.18, 0.040, 0.050, 0.82, "metal")
    w.box(-2.110, 1.05, 1.18, 0.030, 0.090, 0.12, "rail_bumper")
    w.box(2.105, 1.05, 0.08, 0.040, 0.050, 0.92, "metal")
    w.box(2.110, 1.05, 0.08, 0.030, 0.090, 0.12, "rail_bumper")
    for x in (-0.44, -0.24, -0.04, 0.16, 0.36):
        w.box(x, 2.405, 1.90, 0.035, 0.12, 0.035, "metal")
    w.box(0.05, 2.34, 1.90, 1.02, 0.035, 0.035, "metal")
    w.write("ward_clinical_details.obj")


def main() -> None:
    write_materials()
    shell()
    bed()
    bedside_table()
    iv_stand()
    monitor()
    curtain()
    door()
    medical_headwall()
    overbed_light()
    clinical_details()


if __name__ == "__main__":
    main()
