from __future__ import annotations

import json
import struct
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs" / "ASSET_OPTIMIZATION_REPORT.md"


ASSETS = [
    "assets/rooms/ambulance/imported/patient_stretcher_modern.glb",
    "assets/rooms/ambulance/imported/medical_cabinet.glb",
    "assets/rooms/ambulance/imported/medical_equipment.glb",
    "assets/rooms/ambulance/imported/patient_monitor.glb",
    "assets/rooms/ambulance/imported/oxygen_cylinders.glb",
    "assets/rooms/ambulance/imported/medical_bag.glb",
    "assets/rooms/ambulance/imported/iv_stand.glb",
    "assets/characters/nurse_ambulance/nurse_actor_rigged.glb",
]


@dataclass
class AssetStats:
    path: str
    size_mb: float
    vertices: int
    triangles: int
    meshes: int
    primitives: int
    materials: int
    textures: int
    images: int
    skins: int
    animations: int
    morph_targets: int
    extensions: str


def read_glb_json(path: Path) -> dict:
    data = path.read_bytes()
    if len(data) < 20 or data[0:4] != b"glTF":
        raise ValueError("not a GLB 2.0 file")
    version, _length = struct.unpack_from("<II", data, 4)
    if version != 2:
        raise ValueError(f"unsupported GLB version {version}")
    chunk_length, chunk_type = struct.unpack_from("<II", data, 12)
    if chunk_type != 0x4E4F534A:
        raise ValueError("first GLB chunk is not JSON")
    json_bytes = data[20:20 + chunk_length]
    return json.loads(json_bytes.decode("utf-8"))


def accessor_count(doc: dict, accessor_index: int | None) -> int:
    if accessor_index is None:
        return 0
    accessors = doc.get("accessors", [])
    if accessor_index < 0 or accessor_index >= len(accessors):
        return 0
    return int(accessors[accessor_index].get("count", 0))


def inspect_asset(relative: str) -> AssetStats:
    path = ROOT / relative
    doc = read_glb_json(path)
    vertices = 0
    triangles = 0
    primitives = 0
    morph_targets = 0
    for mesh in doc.get("meshes", []):
        for primitive in mesh.get("primitives", []):
            primitives += 1
            attributes = primitive.get("attributes", {})
            position_count = accessor_count(doc, attributes.get("POSITION"))
            vertices += position_count
            indices_count = accessor_count(doc, primitive.get("indices"))
            if indices_count:
                triangles += indices_count // 3
            else:
                triangles += position_count // 3
            morph_targets += len(primitive.get("targets", []))

    extensions = sorted(set(doc.get("extensionsUsed", [])) | set(doc.get("extensionsRequired", [])))
    return AssetStats(
        path=relative,
        size_mb=path.stat().st_size / (1024.0 * 1024.0),
        vertices=vertices,
        triangles=triangles,
        meshes=len(doc.get("meshes", [])),
        primitives=primitives,
        materials=len(doc.get("materials", [])),
        textures=len(doc.get("textures", [])),
        images=len(doc.get("images", [])),
        skins=len(doc.get("skins", [])),
        animations=len(doc.get("animations", [])),
        morph_targets=morph_targets,
        extensions=", ".join(extensions) if extensions else "-",
    )


def budget_label(stats: AssetStats) -> str:
    if stats.triangles > 500_000 or stats.size_mb > 40.0:
        return "critical"
    if stats.triangles > 150_000 or stats.size_mb > 20.0:
        return "high"
    if stats.triangles > 80_000 or stats.size_mb > 12.0:
        return "watch"
    return "ok"


def markdown_table(rows: list[AssetStats]) -> str:
    header = (
        "| Asset | MB | Verts | Tris | Materials | Textures | Skins | Clips | Extensions | Budget |\n"
        "|---|---:|---:|---:|---:|---:|---:|---:|---|---|\n"
    )
    lines = [header]
    for row in rows:
        lines.append(
            f"| `{row.path}` | {row.size_mb:.2f} | {row.vertices} | {row.triangles} | "
            f"{row.materials} | {row.textures} | {row.skins} | {row.animations} | "
            f"{row.extensions} | {budget_label(row)} |\n"
        )
    return "".join(lines)


def write_report(rows: list[AssetStats]) -> None:
    critical = [row for row in rows if budget_label(row) == "critical"]
    content = f"""# Asset Optimization Report

Generated by `tools/inspect_runtime_assets.py`.

## Runtime Asset Snapshot

{markdown_table(rows)}
## Safe Optimization Rules

- Keep source GLB files in `assets/rooms/ambulance/imported`.
- Write runtime copies to `assets/rooms/ambulance/runtime`.
- Do not export Draco or Meshopt compressed GLB until ExoEngine explicitly supports decoding those extensions.
- Safe current operations: prune unused data, deduplicate accessors/materials, weld/reorder vertices, simplify geometry, resize textures, and keep standard GLB 2.0 output.
- Revalidate optimized copies before changing room JSON.

## External References

- VIGIL demonstrates survival-horror room staging with fixed-camera thinking: https://github.com/EmreDogann/VIGIL
- Permafrost Engine is a useful OpenGL 3.3 reference for GPU skinning, batching, and streaming buffers: https://github.com/eduard-permyakov/permafrost-engine
- glTF Transform should be used for inspect/optimize reports: https://gltf-transform.dev/cli
- meshoptimizer is the future route for vertex-cache and simplification work: https://github.com/zeux/meshoptimizer
- Khronos glTF Validator should be used for spec validation: https://github.com/KhronosGroup/glTF-Validator

## Recommended Next Pass

1. Create `assets/rooms/ambulance/runtime`.
2. For each critical asset, produce an optimized GLB copy without compression extensions.
3. Keep visual comparison screenshots before switching room JSON from `imported` to `runtime`.
4. Add validator budget warnings after the optimized copies exist.

Critical assets in this scan: {len(critical)}.
"""
    REPORT.write_text(content, encoding="utf-8")


def main() -> None:
    rows = [inspect_asset(path) for path in ASSETS if (ROOT / path).exists()]
    write_report(rows)
    print(f"Wrote {REPORT}")


if __name__ == "__main__":
    main()
